// Array data used by 'ReturnBorLink' function (below)
var BorLink = [];
BorLink["Barking and Dagenham"] = ["http://www.lbbd.gov.uk/", "http://www.lbbd.gov.uk/environment/planning/pages/planninghome.aspx"]
BorLink["Barnet"] = ["http://www.barnet.gov.uk/", "http://www.barnet.gov.uk/planning/"]
BorLink["Bexley"] = ["http://www.bexley.gov.uk/", "http://www.bexley.gov.uk/index.aspx?articleid=595"]
BorLink["Brent"] = ["http://www.brent.gov.uk/", "http://www.brent.gov.uk/planning.nsf"]
BorLink["Bromley"] = ["http://www.bromley.gov.uk/", "http://www.bromley.gov.uk/info/200074/planning"]
BorLink["Camden"] = ["http://www.camden.gov.uk/", "http://www.camden.gov.uk/ccm/navigation/environment/planning-and-built-environment/"]
BorLink["City of London"] = ["http://www.corpoflondon.gov.uk/", "http://www.cityoflondon.gov.uk/services/environment-and-planning/planning/Pages/default.aspx"]
BorLink["Croydon"] = ["http://www.croydon.gov.uk/", "http://www.croydon.gov.uk/planningandregeneration/"]
BorLink["Ealing"] = ["http://www.ealing.gov.uk/", "http://www.ealing.gov.uk/info/200074/planning/"]
BorLink["Enfield"] = ["http://www.enfield.gov.uk/", "http://www.enfield.gov.uk/info/100007/planning_land_and_place_shaping/"]
BorLink["Greenwich"] = ["http://www.royalgreenwich.gov.uk/", "http://www.royalgreenwich.gov.uk/info/200074/planning/"]
BorLink["Hackney"] = ["http://www.hackney.gov.uk/", "http://www.hackney.gov.uk/planning.htm"]
BorLink["Hammersmith and Fulham"] = ["http://www.lbhf.gov.uk/", "http://www.lbhf.gov.uk/Directory/Environment_and_Planning/Planning/"]
BorLink["Haringey"] = ["http://www.haringey.gov.uk/", "http://www.haringey.gov.uk/services/planning_and_building_control/planning-mainpage.htm"]
BorLink["Harrow"] = ["http://www.harrow.gov.uk/", "http://www.harrow.gov.uk/info/200074/planning/"]
BorLink["Havering"] = ["http://www.havering.gov.uk/", "http://www.havering.gov.uk/Pages/Category/Planning.aspx"]
BorLink["Hillingdon"] = ["http://www.hillingdon.gov.uk/", "http://www.hillingdon.gov.uk/index.jsp?articleid=7727"]
BorLink["Hounslow"] = ["http://www.hounslow.gov.uk/", "http://www.hounslow.gov.uk/planning/"]
BorLink["Islington"] = ["http://www.islington.gov.uk/", "http://www.islington.gov.uk/services/planning/Pages/default.aspx"]
BorLink["Kensington and Chelsea"] = ["http://www.rbkc.gov.uk/", "http://www.rbkc.gov.uk/planningandbuildingcontrol.aspx"]
BorLink["Kingston upon Thames"] = ["http://www.kingston.gov.uk/", "http://www.kingston.gov.uk/info/200155/planning/263/find_a_planning_application_or_appeal/"]
BorLink["Lambeth"] = ["http://www.lambeth.gov.uk/", "http://www.lambeth.gov.uk/planning-and-building-control/planning-applications-and-policies/search-planning-applications"]
BorLink["Lewisham"] = ["http://www.lewisham.gov.uk/", "http://www.lewisham.gov.uk/myservices/planning/Pages/default.aspx"]
BorLink["Merton"] = ["http://www.merton.gov.uk/", "http://www.merton.gov.uk/planning"]
BorLink["Newham"] = ["http://www.newham.gov.uk/", "http://www.newham.gov.uk/Planning/"]
BorLink["Redbridge"] = ["http://www.redbridge.gov.uk/", "http://www.redbridge.gov.uk/Planning/"]
BorLink["Richmond upon Thames"] = ["http://www.richmond.gov.uk/", "http://www.richmond.gov.uk/home/environment/planning.htm"]
BorLink["Southwark"] = ["http://www.southwark.gov.uk/", "http://www.southwark.gov.uk/info/485/planning_applications/554/search_for_planning_applications"]
BorLink["Sutton"] = ["http://www.sutton.gov.uk/", "https://www.sutton.gov.uk/index.aspx?articleid=648"]
BorLink["Tower Hamlets"] = ["http://www.towerhamlets.gov.uk/", "http://www.towerhamlets.gov.uk/lgnl/environment_and_planning/planning.aspx"]
BorLink["Waltham Forest"] = ["http://www.walthamforest.gov.uk/", "http://www.walthamforest.gov.uk/Pages/Category/Planning.aspx"]
BorLink["Wandsworth"] = ["http://www.wandsworth.gov.uk/", "http://www.wandsworth.gov.uk/info/200074/planning/"]
BorLink["Westminster"] = ["http://www.westminster.gov.uk/", "http://www.westminster.gov.uk/search-planning-applications-and-decisions/"]